package net.whydah.admin;
public class ConstantValue {
	public static final String USERTICKET = "userticket";
	public static final String REDIRECT = "redirect";
	public static final String MYURI = "myuri";
	public static final String SESSIONCHECK = "SessionCheck";
	public static final String USERCHECKOUT = "UserCheckout";
	public static final String REDIRECT_URI = "redirectURI";
	public static final String LOGO_URL = "logoURL";
	public static final String APP_LINKS = "appLinks";
	public static final String LOGIN_ERROR = "loginError";
	public static final String IAM_MODE = "iammode";
	public static final String USER = "user";
	public static final String PASSWORD = "password";
	public static final String WHYDAH_VERSION = "version";
	public static final String CSRFtoken = "CSRFtoken";
	public static final String CELL_PHONE = "cellphone";
	public static final String APP_NAMES = "appNames";
	public static final String DEFAULT_REDIRECT = "welcome";
	public static final String ADDRESS = "address";
	public static final String APPLICATIONNAME = "appName";
	public static final String APPLICATIONID = "appId";
	public static final String USERTOKEN = "usertoken";
	public static final String CRMCUSTOMER = "CRMcustomer";
	public static final String USERACTIVITIES = "useractivities";
	public static final String USERACTIVITIES_SIMPLIFIED = "useractivities_simple";
	public static final String REALNAME = "realname";
	public static final String USER_TOKEN_ID = "usertokenid";
	public static final String PHONE_NUMBER = "phonenumber";
	public static final String SECURITY_LEVEL = "securitylevel";
	public static final String EMAIL = "email";
	public static final String DEFCON = "defcon";
	public static final String PERSON_REF = "personRef";
	public static final String JSON_DATA = "jsondata";
	public static final String XML_DATA = "xmldata";
	public static final String SIGNUPENABLED = "signupEnabled";
	public static final String USERPASSWORDLOGINENABLED = "userpasswordLoginEnabled";
	public static final String NAME="name";
	public static final String USERNAME="username";
	public static final String FIRSTNAME = "firstname";
	public static final String LASTNAME = "lastname";
	public static final String PIN = "pin";
	public static final String COMPANY = "company";
	public static final String COMMENT = "comment";
	public static final String ADDRESS_LINE = "addressLine";
	public static final String ADDRESS_LINE1 = "addressLine1";
	public static final String ADDRESS_LINE2 = "addressLine2";
	public static final String STREETADDRESS = "streetAddress";
	public static final String ZIPCODE = "zipcode";
	public static final String POSTALCODE = "postalCode";
	public static final String CITY = "city";
	public static final String POSTALCODE2 = "postalcode";
	public static final String POSTALCITY = "postalcity";
	public static final String OIDADDRESS = "oidstreetaddress";
	public static final String ROLE_ID = "roleid";
	public static final String PHONE_NO="phoneNo";
	public static final String TOKEN = "token";
	public static final String HEALTH = "health";
	public static final String SECURITYTOKENSERVICEHEALTH = "securitytokenservice";
	public static final String USERADMINSERVICEHEALTH = "useradminservice";
	public static final String CRMSERVICEHEALTH = "crmservice";
	public static final String COUNTRYCODE = "countryCode";
	public static final String ERROR="error";
	public static final String ADDRESS_TAG="tag";
	public static final String USEASDEFAULT = "default";
	public static final String ROLENAME= "roleName";
	public static final String ROLEVALUE= "roleValue";
	public static final String APP_TOKEN_ID = "apptokenid";
	public static final String ADDRESS_LABEL = "addresslabel";
	
	//pin troubleshoot
	public static final String PIN_TROUBLESHOOT_TYPE="code";
	public static final String PIN_TROUBLESHOOT_TYPE_DESCRIPTION="errorCodeDescripton";
	public static final String PIN_TROUBLESHOOT_SMS_RESPONSE="smsResponse";
	
	
	public static final String LINE_SEPARATOR = System.getProperty("line.separator");
	public static final String HTML_LINE_SEPARATOR = "<br/>";
	
}